---

site:
    name: Max's Blog
    baseURL: "https://maxstanley.uk"
authors:
    MaxS:
        firstName: Max
        lastName: Stanley
        email: maxahstanley@outlook.com
        twitter: "@maxahstanley"
