name: Publish Site

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      MM_VERSION: 0.2.0

    steps:
      - uses: actions/checkout@v2

      - name: Build masterful-minimalism source
        run: |
          wget https://github.com/maxstanley/masterful-minimalism/archive/refs/tags/v$MM_VERSION.zip -O masterful-minimalism.zip
          unzip masterful-minimalism.zip
          (cd masterful-minimalism-$MM_VERSION/; go build -v)
          cp masterful-minimalism-$MM_VERSION/masterful-minimalism .

      - name: Create site using masterful-minimalism
        run: |
          ./masterful-minimalism -input=src/
          cp -r src/static/* output/
          echo "maxstanley.uk" > output/CNAME

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge Cloudflare Cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
